- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: kForce-rg
        location: eastus2
   
    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: kForce-rg
        name: vNet
        address_prefixes: "10.0.0.0/16"
    
    - name: Add subnet 01
      azure_rm_subnet:
        resource_group: kForce-rg
        name: public-subnet-1
        address_prefix: "10.0.1.0/24"
        virtual_network: vNet

    - name: Add subnet 02
      azure_rm_subnet:
        resource_group: kForce-rg
        name: public-subnet-2
        address_prefix: "10.0.2.0/24"
        virtual_network: vNet


    - name: Create public IP address
      azure_rm_publicipaddress:
        resource_group: kForce-rg
        allocation_method: Static
        name: pip
      register: output_ip_address

    - name: Output public IP
      debug:
        msg: "The public IP is {{ output_ip_address.state.ip_address }}"

    - name: Create Network Security Group
      azure_rm_securitygroup:
        resource_group: kForce-rg
        name: kForceNetworkSecurityGroup
        rules:
          - name: 'allow_rdp'
            protocol: Tcp
            destination_port_range: 3389
            access: Allow
            priority: 1001
            direction: Inbound
          - name: 'allow_web_traffic'
            protocol: Tcp
            destination_port_range:
              - 80
              - 443
            access: Allow
            priority: 1002
            direction: Inbound

    - name: Create a network interface
      azure_rm_networkinterface:
        name: nic
        resource_group: kForce-rg
        virtual_network: vNet
        subnet_name: public-subnet-1
        security_group: kForceNetworkSecurityGroup
        ip_configurations:
          - name: default
            public_ip_address_name: pip
            primary: True

    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: kForce-rg
        name: win-vm-1
        vm_size: Standard_B1s
        admin_username: azureuser
        admin_password: "kForce123@@"
        network_interfaces: nic
        os_type: Windows
        image:
            offer: WindowsServer
            publisher: MicrosoftWindowsServer
            sku: 2019-Datacenter-gensecond
            version: latest
      no_log: false