- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ region }}"
   
    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: "{{ resource_group }}"
        name: vNet
        address_prefixes: "10.0.0.0/16"
    
    - name: Add subnet 01
      azure_rm_subnet:
        resource_group: "{{ resource_group }}"
        name: public-subnet-1
        address_prefix: "10.0.1.0/24"
        virtual_network: vNet

    - name: Add subnet 02
      azure_rm_subnet:
        resource_group: "{{ resource_group }}"
        name: public-subnet-2
        address_prefix: "10.0.2.0/24"
        virtual_network: vNet


    - name: Create public IP address
      azure_rm_publicipaddress:
        resource_group: "{{ resource_group }}"
        allocation_method: Static
        name: pip
      register: output_ip_address

    - name: Create public IP address
      azure_rm_publicipaddress:
        resource_group: "{{ resource_group }}"
        allocation_method: Static
        name: lbpip
      register: output_lbpip_address      

    - name: Output public IP
      debug:
        msg: "The public IP is {{ output_ip_address.state.ip_address }}"

    - name: Create Network Security Group
      azure_rm_securitygroup:
        resource_group: "{{ resource_group }}"
        name: kForceNetworkSecurityGroup
        rules:
          - name: 'allow_rdp'
            protocol: Tcp
            destination_port_range: 3389
            access: Allow
            priority: 1001
            direction: Inbound

          - name: 'allow_web_traffic'
            protocol: Tcp
            destination_port_range:
              - 80
              - 443
            access: Allow
            priority: 1002
            direction: Inbound

          - name: 'allow_powershell_remoting'
            protocol: Tcp
            destination_port_range: 
              - 5985
              - 5986
            access: Allow
            priority: 1003
            direction: Inbound

    - name: Create a network interface
      azure_rm_networkinterface:
        name: nic
        resource_group: "{{ resource_group }}"
        virtual_network: vNet
        subnet_name: public-subnet-1
        security_group: kForceNetworkSecurityGroup
        ip_configurations:
          - name: default
            public_ip_address_name: pip
            primary: True

    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: win-vm
        vm_size: "{{ vm_size }}"
        admin_username: "{{ username }}" 
        admin_password: "{{ password }}" 
        network_interfaces: nic
        os_type: "{{ os_type }}"
        image:
            offer: "{{ offer }}"
            publisher: "{{ publisher }}"
            sku: "{{ sku }}"
            version: "{{ version }}"
      no_log: false

    - name: Creating a Load Balancer
      azure_rm_loadbalancer:
        resource_group: "{{ resource_group }}"
        name: MainLoadBalancer
        frontend_ip_configurations:
          - name: frontendipconf0
            public_ip_address: lbpip 
        probes:
          - name: prob0
            port: 80
        inbound_nat_pools:
          - name: inboundnatpool0
            frontend_ip_configuration_name: frontendipconf0
            protocol: Tcp
            frontend_port_range_start: 80
            frontend_port_range_end: 81
            backend_port: 8080
        load_balancing_rules:
          - name: lbrbalancingrule0
            frontend_ip_configuration: frontendipconf0
            backend_address_pool: backendaddrpool0
            frontend_port: 80
            backend_port: 80
            probe: prob0
        inbound_nat_rules:
          - name: inboundnatrule0
            backend_port: 8080
            protocol: Tcp
            frontend_port: 8080
            frontend_ip_configuration: frontendipconf0

    - name: Create VM script extension to enable HTTPS WinRM listener
      azure_rm_virtualmachineextension:
        name: winrm-extension
        resource_group: "{{ resource_group }}"
        virtual_machine_name: win-vm
        publisher: Microsoft.Compute
        virtual_machine_extension_type: CustomScriptExtension
        type_handler_version: '1.9'
        settings: '{"fileUris": ["https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1"],"commandToExecute": "powershell -ExecutionPolicy Unrestricted -File ConfigureRemotingForAnsible.ps1"}'
        auto_upgrade_minor_version: true

    - name: Get facts for one Public IP
      azure_rm_publicipaddress_info:
        resource_group: "{{ resource_group }}"
        name: pip
      register: publicipaddresses

    - name: set public ip address fact
      set_fact: publicipaddress="{{ publicipaddresses | json_query('publicipaddresses[0].ip_address')}}"

    - name: wait for the WinRM port to come online
      wait_for:
        port: 5986
        host: '{{ publicipaddress }}'
        timeout: 600
