- name: Create Azure App Service
  hosts: localhost
  connection: local
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ region }}"

    - name: "Create app service plan."
      azure_rm_appserviceplan:
        name: "{{ app_service }}-plan"
        resource_group: "{{ resource_group }}"
        is_linux: true
        sku: "{{ app_service_plan_sku }}"
        location: "{{ region}}"

    - name: "Deploy application from image."
      azure_rm_webapp:
        name: "{{ app_service }}"
        plan: "{{ app_service }}-plan"
        resource_group: "{{ resource_group}}"
        container_settings:
          name: "mcr.microsoft.com/appsvc/staticsite:latest"
        purge_app_settings: true
        app_state: restarted
        https_only: true
        location: "{{ region }}"

    - name: "Create v network for webapp."
      azure_rm_virtualnetwork:
        name: "{{ app_service }}-vnet"
        resource_group: "{{ resource_group }}"
        address_prefixes_cidr:
          - "10.2.0.0/27"

    - name: "Create default subnet for virtual network."
      azure_rm_subnet:
        name: "default"
        resource_group: "{{ resource_group}}"
        virtual_network_name: "{{ app_service }}-vnet"
        address_prefix_cidr: "10.2.0.0/28"
        delegations:
          - name: "Microsoft.Web/serverFarms"
            serviceName: "Microsoft.Web/serverFarms"      

    - name: "Configure web app with virtual network."
      azure_rm_webappvnetconnection:
        name: "{{ app_service}}"
        resource_group: "{{ resource_group}}"
        vnet_name: "{{ app_service_name }}-vnet"
        subnet: "default"                

    - name: "Display new url."
      debug:
        msg: "Application is now available at https://{{ app_service_name }}.azurewebsites.net/"