- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: kForce-rg
        location: eastus
   
    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: kForce-rg
        name: vNet
        address_prefixes: "10.0.0.0/16"
    
    - name: Add subnet
      azure_rm_subnet:
        resource_group: kForce-rg
        name: public_subnet_1
        address_prefix: "10.0.1.0/24"
        virtual_network: vNet

    - name: Add subnet
      azure_rm_subnet:
        resource_group: kForce-rg
        name: public_subnet_2
        address_prefix: "10.0.2.0/24"
        virtual_network: vNet


    - name: Create public IP address
      azure_rm_publicipaddress:
        resource_group: kForce-rg
        allocation_method: Static
        name: public-static-ip
      register: output_ip_address

    - name: Output public IP
      debug:
        msg: "The public IP is {{ output_ip_address.state.ip_address }}"
